services:
  web:
    image: ghcr.io/stinejennna/devops-exam:staging
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=movies;Username=postgres;Password=postgres

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: