name: .NET CI + SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/stinejennna/devops-exam:staging \
            -t ghcr.io/stinejennna/devops-exam:latest \
            -f ./DevOpsExamMovie/Dockerfile \
            .

      - name: Push Docker images
        run: |
          docker push ghcr.io/stinejennna/devops-exam:staging
          docker push ghcr.io/stinejennna/devops-exam:latest
          
      - name: Create release notes
        uses: ncipollo/release-action@v1
        with: 
          tag: ${{ steps.get_version.outputs.VERSION }}
          generateReleaseNotes: true
          body: |
            This release includes the following container image:
            ghcr.io/stinejennna/devops-exam:latest 

      - name: Begin SonarQube analysis
        run: |
          dotnet sonarscanner begin \
            /k:"MovieRater" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Restore local tools
        run: dotnet tool restore

      - name: Run mutation tests (Stryker)
        run: dotnet stryker

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"