name: .NET CI + SonarQube + Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore

      - name: Begin SonarQube analysis
        run: |
          dotnet sonarscanner begin \
            /k:"MovieRater" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

      - name: Restore tools
        run: dotnet tool restore

      - name: Run mutation tests
        run: dotnet stryker

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/stinejennna/devops-exam:staging \
            -f ./DevOpsExamMovie/Dockerfile \
            .

      - name: Push Docker image
        run: docker push ghcr.io/stinejennna/devops-exam:staging

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: docker-compose.yaml
          target: /root/dowa

      - name: Deploy to Contabo
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            mkdir -p /root/dowa
            cd /root/dowa
            docker compose pull
            docker compose up -d

        - name: Run K6 test
          uses: grafana/run-k6-action@v1
          with:
            path: k6-test.js

        - name: Run E2E test
          run: |
           curl -X POST http://YOUR_SERVER_IP:8000/api/movies \
                -H "Content-Type: application/json" \
                -d '{"title":"Batman","rating":8}'
                  
          curl http://YOUR_SERVER_IP:8000/api/movies